### PR TITLE
Set mode option

### PR DESCRIPTION
**Pull request by jaap3**
Fixes issue #24

### CODE REVIEW

**Comment by kota65535** [comment]
@jaap3 Thank you for contributing!
Now CI is failing, but maybe it is because `npm run build` is not run yet and `dist/index.js` is not committed.
It should be automatically run as pre-commit hook thanks to husky.

**Comment by jaap3** [comment]
Ah, I used the GitHub editor in the browser, I don't think commit hooks run that way. Thanks for looking into this.

**Comment by kota65535** [comment]
@jaap3 Do you want to continue with this PR? If not, I'm going to close this now and merge #26 instead.

**Comment by jaap3** [comment]
Please merge the other one, thanks!

**Pull request closed without merging**
